---
kind: pipeline
type: docker
name: getsite
volumes: # 声明数据卷（此为服务器中的实际目录）
  - name: node_modules # 数据卷名称
    host: # Host Volume
      path: /home/drone/autolink/node_modules # 宿主机目录    #绝对路径
  - name: cache
    host:
      path: /root/.cache
node:
  a: racknerd
  c: d
steps: # 定义管道的执行步骤
  - name: deploy # 步骤名称
    image: aiboboxx/node:latest # 当前步骤使用的镜像
    depends_on: [clone] # 依赖的步骤
    volumes: # 挂载数据卷（此为容器内的目录）
      - name: node_modules # 数据卷名称
        path: /drone/src/node_modules # 容器内目录 绝对路径
      - name: cache
        path: /root/.cache
    commands: # 当前步骤执行的命令
      - export runId=123456
      - pwd # 查看当前目录
      - apt-get install ttf-wqy-zenhei -y
      - npm install # 安装node_modules包
      #- ls
      - Xvfb -ac :7 -screen 0 1280x1024x8 &
      - export DISPLAY=:7
      - node autolink.js
trigger:
  branch:
  - main
  event:
  - push

