name: freeok_sign_db

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  FREEOK_ACCOUNTS: ${{ secrets.FREEOK_ACCOUNTS }}
  FREEOK_COOKIES: ${{ secrets.FREEOK_COOKIES }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2 
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Cache node_modules
              uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
              env:
                cache-name: cache-node-modules
              with:
                path: node_modules
                key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替    
            - name: Run install
              run: npm install
            - name: Run Script
              run: node freeok_sign.js
                
            - name: Create report file
              run: date +%s > report.txt
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                COMMIT_MESSAGE: Add build artifact
                PULL_REQUEST_TITLE: Add build artifact
