name: regAuto8.js

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '50 2,6,10,14,18,22 * * *'
  # watch:
  #   types: started
    
env:
  FREEOK_ACCOUNTS: ${{ secrets.FREEOK_ACCOUNTS }}
  FREEOK_COOKIES: ${{ secrets.FREEOK_COOKIES }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2 
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '16.x'
            - name: Cache node_modules
              uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
              env:
                cache-name: cache-node-modules
              with:
                path: node_modules
                key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替    
            - name: Run install
              run: npm install
            - name: freeok_regAuto8.js
              run: node freeok_regAuto8.js  # > report.txt             
            - name: Commit report
              run: |
                echo  "regAuto8运行时间：`date '+%Y%m%d %H%M%S'`" > report.txt
                git config --global user.name 'aiboboxx' 
                git config --global user.email 'aiboboxx@gmail.com'
                git add .
                git commit -m "Automated report $(date '+%Y/%m/%d')"
                git push
              
