name: testyml
on:
  workflow_dispatch:
env:
  AT_GIT_ACTION: true
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Cache multiple paths
              uses: actions/cache@v2
              with:
                path: |
                  ~/cache
                  !~/cache/exclude
                key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}  
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node test.js